INSERT INTO `memorycache`.`produtos` VALUES(null,'Caneta Bic Azul',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caneta Bic Vermelha',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caneta Bic Preta',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Lapis Faber Castle 2B',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Apontador Vermelho',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Apontador Azul',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Borracha branca',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Borracha Dual Colors',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caixa Lapis de cor 12 cores',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caixa Lapis de cor 24 cores',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Lapiseira 0.5',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Lapiseira 0.7',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Lapiseira 0.9',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Lapiseira 2.0',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Conjunto de grafite 0.5',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Conjunto de grafite 0.7',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Conjunto de grafite 0.9',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Conjunto de grafite 2.0',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caderno 10 materias',true,1000,1);
INSERT INTO `memorycache`.`produtos` VALUES(null,'Caderno 12 materia',true,1000,1);